# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=64, verbose_name='region')),
                ('country', models.CharField(max_length=64, verbose_name='country')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'verbose_name': 'structure',
                'ordering': ['region'],
                'verbose_name_plural': 'structures',
            },
        ),
    ]
